version: "3.8"

services:
  db:
    image: postgres:10.16-alpine
    container_name: "db-django-client"
    environment:
      - POSTGRES_DB=client-django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "7432:5432"
